name       : python-smartypants
version    : 2.0.1
release    : 2
source     :
    - https://github.com/leohemsted/smartypants.py/archive/refs/tags/v2.0.1.tar.gz : b98191911ff3b4144ef8ad53e776a2d0ad24bd508a905c6ce523597c40022773
license    :
    - BSD-2-Clause
    - BSD-3-Clause
component  : programming.python
summary    : python-smartypants is a Python fork of SmartyPants
description: |
    python-smartypants is a Python fork of SmartyPants.
builddeps  :
    - pkgconfig(python3)
build      : |
    %python3_setup
install    : |
    %python3_install
